# Generated by Django 3.0.5 on 2020-05-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='name',
        ),
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.CharField(default='test title', max_length=50, verbose_name='标题'),
            preserve_default=False,
        ),
    ]
