# Generated by Django 3.0.5 on 2020-06-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20200517_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='content',
            field=models.CharField(blank=((1, 'HTML'), (2, '最新文章'), (3, '最热文章'), (4, '最近评论')), help_text='如果设置的不是HTML类型，可为空', max_length=500, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='display_type',
            field=models.PositiveIntegerField(choices=[(1, 'HTML'), (2, '最新文章'), (3, '最热文章'), (4, '最近评论')], default=1, verbose_name='展示类型'),
        ),
    ]
